# Conversion factor from 4xCO2 to 2xCO2 and doubling CO2 cases

Theme Song: Hot In Here<br>
Artist: Nelly<br>
Album: Nellyville<br>
Released: 2002

In [1]:
from fair.forcing.ghg import meinshausen, etminan
import pandas as pd
import numpy as np

In [2]:
ghg_obs = pd.read_excel('../data_input/observations/LLGHG_history_AR6_v9_for_archive.xlsx', skiprows=22, sheet_name="mixing_ratios", index_col=0)
for addyear in range(1751,1850):
    ghg_obs.loc[addyear, 'YYYY'] = np.nan
ghg_obs = ghg_obs.sort_index()
ghg_obs = ghg_obs.interpolate()
ghg_obs

CO2        CH4       N2O  HFC-134a  HFC-23     HFC-32  HFC-125  \
YYYY                                                                       
1750  278.300   729.2000  270.1000    0.0000   0.000   0.000218   0.0000   
1751  278.372   729.9840  270.1200    0.0000   0.000   0.000218   0.0000   
1752  278.444   730.7680  270.1400    0.0000   0.000   0.000218   0.0000   
1753  278.516   731.5520  270.1600    0.0000   0.000   0.000218   0.0000   
1754  278.588   732.3360  270.1800    0.0000   0.000   0.000218   0.0000   
...       ...        ...       ...       ...     ...        ...      ...   
2015  399.420  1834.0055  328.3025   83.4145  28.042   9.985158  18.0910   
2016  402.850  1842.1665  329.1240   89.4825  28.950  11.972602  20.4815   
2017  405.000  1849.2365  330.0400   95.7485  29.975  14.153317  23.2450   
2018  407.390  1857.7770  331.1905  101.8415  31.158  16.556241  26.3125   
2019  409.850  1866.3275  332.0910  107.5910  32.414  19.980503  29.4030   

      HFC-143a  HFC-152a  HFC-227ea  ...  C7F16  C8F18   CFC-112  CFC-112a  \
YYYY                                 ...                                     
1750    0.0000    0.0000   0.000004  ...   0.00  0.000  0.000000     0.000   
1751    0.0000    0.0000   0.000004  ...   0.00  0.000  0.000445     0.000   
1752    0.0000    0.0000   0.000004  ...   0.00  0.000  0.000890     0.000   
1753    0.0000    0.0000   0.000004  ...   0.00  0.000  0.001336     0.000   
1754    0.0000    0.0000   0.000004  ...   0.00  0.000  0.001781     0.000   
...        ...       ...        ...  ...    ...    ...       ...       ...   
2015   17.5655    6.5970   1.096239  ...   0.11  0.091  0.412000     0.066   
2016   19.1555    6.6600   1.205802  ...   0.11  0.091  0.412000     0.067   
2017   20.8340    6.8175   1.327504  ...   0.11  0.091  0.412000     0.067   
2018   22.4245    7.0135   1.457735  ...   0.11  0.091  0.412000     0.067   
2019   24.0120    7.1345   1.594721  ...   0.11  0.091  0.412000     0.067   

      CFC-113a  CFC-114a  HCFC-133a   HCFC-31  HCFC-124  YYYY  
YYYY                                                           
1750  0.000000  0.000000   0.000000  0.000000  0.000000   NaN  
1751  0.000104  0.001520   0.000061  0.000108  0.004921   NaN  
1752  0.000208  0.003041   0.000121  0.000216  0.009843   NaN  
1753  0.000313  0.004561   0.000182  0.000324  0.014764   NaN  
1754  0.000417  0.006082   0.000243  0.000432  0.019685   NaN  
...        ...       ...        ...       ...       ...   ...  
2015  0.680000  1.050000   0.398970  0.083000  1.020000   NaN  
2016  0.680000  1.040000   0.425010  0.083000  1.020000   NaN  
2017  0.680000  1.040000   0.439890  0.083000  1.020000   NaN  
2018  0.680000  1.040000   0.438960  0.083000  1.020000   NaN  
2019  0.680000  1.040000   0.431520  0.083000  1.020000   NaN  

[270 rows x 53 columns]

In [3]:
co2_pi = ghg_obs.loc[1750,'CO2']
ch4_pi = ghg_obs.loc[1750,'CH4']
n2o_pi = ghg_obs.loc[1750,'N2O']

co2_1850 = ghg_obs.loc[1850,'CO2']
ch4_1850 = ghg_obs.loc[1850,'CH4']
n2o_1850 = ghg_obs.loc[1850,'N2O']

co2_2011 = ghg_obs.loc[2011,'CO2']
ch4_2011 = ghg_obs.loc[2011,'CH4']
n2o_2011 = ghg_obs.loc[2011,'N2O']

co2_2019 = ghg_obs.loc[2019,'CO2']
ch4_2019 = ghg_obs.loc[2019,'CH4']
n2o_2019 = ghg_obs.loc[2019,'N2O']

In [4]:
m4x = meinshausen(np.array([4*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)
m2x = meinshausen(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)
m2x[0]/m4x[0]

0.47630403979167685

In [5]:
e4x = etminan(np.array([4*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)
e2x = etminan(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)
e2x[0]/e4x[0]

0.4780337002434125

In [6]:
e2x[0]

3.80195857817616

In [7]:
m2x[0]

3.746826975133355

In [8]:
etminan(np.array([2*co2_2011, ch4_2011, n2o_2011]), Cpi=np.array([co2_2011, ch4_2011, n2o_2011]), scale_F2x=False)

array([3.83754147, 0.        , 0.        ])

In [9]:
meinshausen(np.array([2*co2_2011, ch4_2011, n2o_2011]), Cpi=np.array([co2_2011, ch4_2011, n2o_2011]), scale_F2x=False)

array([3.79059855, 0.        , 0.        ])

In [10]:
meinshausen(np.array([284.3*2, ch4_pi, n2o_pi]), Cpi=np.array([284.3, ch4_pi, n2o_pi]), scale_F2x=False)

array([3.7494039, 0.       , 0.       ])

In [11]:
etminan(np.array([co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)

array([2.08539106, 0.62916705, 0.19523587])

In [12]:
meinshausen(np.array([co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)

array([2.05359802, 0.63253836, 0.19482489])

In [13]:
meinshausen(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False) * np.array([1.05, 0.86, 1.07])

array([3.93416832, 0.        , 0.        ])

In [14]:
meinshausen(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)

array([3.74682698, 0.        , 0.        ])

In [15]:
meinshausen(np.array([2*co2_1850, ch4_1850, n2o_1850]), Cpi=np.array([co2_1850, ch4_1850, n2o_1850]), scale_F2x=False) * np.array([1.05, 0.86, 1.07])

array([3.93731869, 0.        , 0.        ])

In [16]:
etminan(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)

array([3.80195858, 0.        , 0.        ])

In [17]:
etminan(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False) * np.array([1.05, 0.86, 1.07])

array([3.99205651, 0.        , 0.        ])

In [18]:
print(etminan(np.array([700, 1800, 323]), Cpi=np.array([389, 1800, 323]), scale_F2x=False))
print(meinshausen(np.array([700, 1800, 323]), Cpi=np.array([389, 1800, 323]), scale_F2x=False))

[3.22707066 0.         0.        ]
[3.18558871 0.         0.        ]


In [19]:
print(etminan(np.array([389, 1800, 323]), Cpi=np.array([180, 1800, 323]), scale_F2x=False))
print(meinshausen(np.array([389, 1800, 323]), Cpi=np.array([180, 1800, 323]), scale_F2x=False))

[4.18614974 0.         0.        ]
[4.12898865 0.         0.        ]


In [20]:
print(etminan(np.array([700, 1800, 323]), Cpi=np.array([180, 1800, 323]), scale_F2x=False))
print(meinshausen(np.array([700, 1800, 323]), Cpi=np.array([180, 1800, 323]), scale_F2x=False))

[7.60776501 0.         0.        ]
[7.52110683 0.         0.        ]


In [21]:
3.22707066 +4.18614974 

7.4132204

In [22]:
3.18558871 + 4.12898865 

7.31457736

### chapter 2 1750

In [23]:
print(etminan(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False))
print(etminan(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

print(meinshausen(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False))
print(meinshausen(np.array([2*co2_pi, ch4_pi, n2o_pi]), Cpi=np.array([co2_pi, ch4_pi, n2o_pi]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

[3.80195858 0.         0.        ]
[3.99205651 0.         0.        ]
[3.74682698 0.         0.        ]
[3.93416832 0.         0.        ]


### Meinshausen et al original 1750

In [24]:
print(etminan(np.array([2*277.15, ch4_pi, 273.87]), Cpi=np.array([277.15, ch4_pi, 273.87]), scale_F2x=False))
print(etminan(np.array([2*277.15, ch4_pi, 273.87]), Cpi=np.array([277.15, ch4_pi, 273.87]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

print(meinshausen(np.array([2*277.15, ch4_pi, 273.87]), Cpi=np.array([277.15, ch4_pi, 273.87]), scale_F2x=False))
print(meinshausen(np.array([2*277.15, ch4_pi, 273.87]), Cpi=np.array([277.15, ch4_pi, 273.87]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

[3.80094215 0.         0.        ]
[3.99098926 0.         0.        ]
[3.74616138 0.         0.        ]
[3.93346945 0.         0.        ]


### Meinshausen CMIP6 1850

In [25]:
print(etminan(np.array([2*284.32, ch4_pi, 273.02]), Cpi=np.array([284.32, ch4_pi, 273.02]), scale_F2x=False))
print(etminan(np.array([2*284.32, ch4_pi, 273.02]), Cpi=np.array([284.32, ch4_pi, 273.02]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

print(meinshausen(np.array([2*284.32, ch4_pi, 273.02]), Cpi=np.array([284.32, ch4_pi, 273.02]), scale_F2x=False))
print(meinshausen(np.array([2*284.32, ch4_pi, 273.02]), Cpi=np.array([284.32, ch4_pi, 273.02]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

[3.80397448 0.         0.        ]
[3.9941732 0.        0.       ]
[3.74928048 0.         0.        ]
[3.93674451 0.         0.        ]


### Etminan 2011 values

In [26]:
print(etminan(np.array([2*389, ch4_pi, 323]), Cpi=np.array([389, ch4_pi, 323]), scale_F2x=False))
print(etminan(np.array([2*389, ch4_pi, 323]), Cpi=np.array([389, ch4_pi, 323]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

print(meinshausen(np.array([2*389, ch4_pi, 323]), Cpi=np.array([389, ch4_pi, 323]), scale_F2x=False))
print(meinshausen(np.array([2*389, ch4_pi, 323]), Cpi=np.array([389, ch4_pi, 323]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

[3.83721632 0.         0.        ]
[4.02907714 0.         0.        ]
[3.79008967 0.         0.        ]
[3.97959416 0.         0.        ]


### chapter 2 2019

In [27]:
print(etminan(np.array([2*co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_2019, ch4_2019, n2o_2019]), scale_F2x=False))
print(etminan(np.array([2*co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_2019, ch4_2019, n2o_2019]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

print(meinshausen(np.array([2*co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_2019, ch4_2019, n2o_2019]), scale_F2x=False))
print(meinshausen(np.array([2*co2_2019, ch4_2019, n2o_2019]), Cpi=np.array([co2_2019, ch4_2019, n2o_2019]), scale_F2x=False)*np.array([1.05, 0.86, 1.07]))

[3.84352774 0.         0.        ]
[4.03570412 0.         0.        ]
[3.79782409 0.         0.        ]
[3.9877153 0.        0.       ]
